"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react"; // Import useEffect and useState
import "./globals.css";
import Navbar from "./component/Navbar";
import { loadGetInitialProps } from "next/dist/shared/lib/utils";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showNavbar, setShowNavbar] = useState(true);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const currentPath = window.location.href;
      console.log(currentPath);
      if (
        currentPath === "http://localhost:3000/" ||
        // currentPath === "https://food-tolu-14g4.vercel.app/" ||
        currentPath.includes("Signin")
      ) {
        setShowNavbar(false);
      } else {
        setShowNavbar(true);
      }
    }
  }, []);

  return (
    <html lang="en">
      <body>
        {showNavbar && <Navbar />}
        {children}
      </body>
    </html>
  );
}
